object Versions {
    const val kotlin = "1.4.32"
    const val androidPlugin = "4.2.0"
    const val gsm = "4.3.3"
    const val crashlytics = "2.1.0"
    const val koin = "3.0.1"
    const val androidMaterial = "1.2.0"
    const val constraintLayout = "2.0.1"
    const val lifecycleExt = "2.4.0-alpha01"
    const val jUnit = "4.13"
    const val mockK = "1.10.0"
    const val archTesting = "1.1.1"
    const val retrofit = "2.9.0"
    const val moshi = "1.9.3"
    const val room = "2.2.5"
    const val coroutines = "1.4.3"
    const val timber = "4.7.1"
    const val navigation = "2.3.0"
    const val anrWatchDog = "1.4.0"
    const val moshiConverter = "2.9.0"
    const val okhttpInterceptor = "4.8.1"
    const val dependencyUpdates = "0.39.0"
}
